# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
